### ISSUE TITLE
Can we compute reference_chosen_logps, reference_rejected_logps offline?

### ISSUE THREAD

**Issue by NouamaneTazi** [eric-mitchell/direct-preference-optimization#29]
Is there a reason why we're not computing `reference_chosen_logps, reference_rejected_logps` using the `reference_model` offline? Wouldn't be faster than dematerializing/remat the model in case of FSDP?

**Comment by eric-mitchell** [comment]
You're right, this would save some compute & memory, though it would slightly complicate the DPO pipeline (adding a pre-caching step). I'm not sure how significant the speedup would be in practice (since the forward/backward of the policy we have to do in either case, and the backward pass is the bottleneck anyway).

Only way to find out for sure is to try it! Wouldn't be too terribly difficult to do, if you want to open a PR :) happy to give feedback if you'd like to give it a go- not sure I'll get to this in the near future myself.

**Comment by eric-mitchell** [comment]
I'll close this for now, but feel free to continue the discussion/re-open if you'd like.

**Comment by NouamaneTazi** [comment]
Thanks, I'll give it a go when I've got time 🙌
