### ISSUE TITLE
does reference free mode work?

### ISSUE THREAD

**Issue by JosephZZ** [eric-mitchell/direct-preference-optimization#38]
Hi just curious, since the feature is implemented in the code but seems not mentioned in the paper. 
Does it work? 
Is it worse or better than using an out of domain SFT model (like those finetuend with alpaca)?

Thank you!

**Comment by eric-mitchell** [comment]
reference-free mode is equivalent to using the uniform policy as the reference model (i.e., one that assigns the same probability to all responses), since then the reference model log prob cancels for the chosen and rejected for all pairs.

In my experience, naively using reference-free DPO works worse than using a real reference model. However, it's possible this is due to response length (autoregressive models will tend to assign lower probability to longer sequences). I'd be curious to see what happens if you do reference-free DPO, but make sure the chosen and rejected responses are the same length! Feel free to re-open if you have any other thoughts or questions.
