### ISSUE TITLE
Question about fine tuning steps(epoch)

### ISSUE THREAD

**Issue by gyuwon12** [eric-mitchell/direct-preference-optimization#58]
Hello, I'm going to learn the SFT model with instruction tuning through DPO. Looking at various examples(https://github.com/huggingface/trl/blob/main/examples/research_projects/stack_llama_2/scripts/README.md) and papers, the fine tuning step varies not just a few times but a few hundred times. Is there no performance to turn step 2 and 3?

Thank you.

**Comment by eric-mitchell** [comment]
Are you asking if we can merge the SFT and DPO steps? Typically doing SFT first is helpful, as DPO only learns the "delta" between the chosen and rejected examples, but if there are (useful) behaviors that appear in *both*, then DPO won't learn them; that's why we need SFT first. Feel free to re-open if this doesn't answer your question.

**Comment by OnceJune** [comment]
@eric-mitchell Hi, from the code the chosen response comes from fp32 forward, and the rejected response comes from fp16 forward, so I don't need a human labeled dataset, instead run the forward twice (one time fp32 and one time fp16) is enough, is that right?
